apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: stock-data-service
  name: stock-data-service
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  selector:
    io.kompose.service: stock-data-service
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: ./kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: stock-data-service
  name: stock-data-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: stock-data-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: ./kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: stock-data-service
    spec:
      containers:
        - image: cnit481group5/stock-data-service
          name: stock-data-service
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}